### ISSUE TITLE
請問?

### ISSUE THREAD

**Issue by eddiechen578** [ycs77/Laravel-shop#1]
下載你的檔案 重新安裝套件 到首頁就出現 伺服器錯誤
怎麼解決??

**Comment by ycs77** [comment]
可以提供你的執行環境(XAMPP 或 Homestead)跟安裝步驟嗎?

**Comment by ycs77** [comment]
現在可以照著 README.md 重新下載、安裝一次，應該不會有問題了。

你是用 Homestead?

**Comment by eddiechen578** [comment]
所以要用homestead嗎 我是用xampp

**Comment by ycs77** [comment]
用 Artisan 的 Server (`php artisan serve`) 和 xampp 的 MySQL

但 PHP 要 **7.1 或 7.2** (7.3不正常)

`APP_URL` 設成 http://localhost:8000

**Comment by eddiechen578** [comment]
謝謝 成功了

**Comment by ycs77** [comment]
不客氣！
