### ISSUE TITLE
我看到你的代碼，商品SKU是單維度的...

### ISSUE THREAD

**Issue by noecs** [ycs77/Laravel-shop#4]
你好，我看到你的代碼，商品SKU是單維度的，有考慮拓展不同維度的嗎例如：手機擁有存儲和顏色區分，衣服擁有顏色和尺碼區分

**Comment by ycs77** [comment]
目前抽時間在做，還沒完成。(#5)

**Comment by ycs77** [comment]
踩了不少的坑，終於完成了，可以下載來玩玩看。(#5)
